project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rust_primer.qmd
        text: Rust Primer
      - href: kubernetes_primer.qmd
        text: Kubernetes Primer
      - href: ipsec_primer.qmd
        text: IPSec Primer
      - href: hdd_tco_summary.qmd
        text: HDD TCO
      - href: ampereone_m_vs_amd_epyc.qmd
        text: Ampere vs AMD
      - href: arista_switch_health_report.qmd
        text: Arista Health

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
